<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnSinhSo.Application\AnSinhSo.Application.csproj" />
    <ProjectReference Include="..\AnSinhSo.Infrastructure\AnSinhSo.Infrastructure.csproj" />
    <ProjectReference Include="..\AnSinhSo.Shared\AnSinhSo.Shared.csproj" />
    <ProjectReference Include="..\AnSinhSo.Contracts\AnSinhSo.Contracts.csproj" />
  </ItemGroup>

</Project>
