<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AnSinhSo.Worker-13b29d2b-67dd-477b-a62a-ec8d509b8afb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnSinhSo.Application\AnSinhSo.Application.csproj" />
    <ProjectReference Include="..\AnSinhSo.Infrastructure\AnSinhSo.Infrastructure.csproj" />
    <ProjectReference Include="..\AnSinhSo.Shared\AnSinhSo.Shared.csproj" />
    <ProjectReference Include="..\AnSinhSo.Contracts\AnSinhSo.Contracts.csproj" />
  </ItemGroup>
</Project>
